### ISSUE TITLE
Lint the Codebase and Create CI/CD workflow for the same

### ISSUE THREAD

**Issue by uzaxirr** [ZeStream/zestream-server#32]
Currently the codebase is not properly linted, when we run `golangci-lint run` in the root of repository we get many errors, so it is desirable to fix them up and create a GitHub action workflow for the same to avoid bumping into this in future

<img width="1134" alt="Screenshot 2023-01-02 at 1 13 49 AM" src="https://user-images.githubusercontent.com/72073401/210182930-fd420a91-80bf-41a5-a09d-e63c8204907b.png">

**Comment by Shofiya2003** [comment]
Hey!
Can I work on the issue?
Here, we need GitHub Action workflow for linting. Right?

**Comment by uzaxirr** [comment]
Hey @Shofiya2003 

Yes, You can work on this. Assigning this to you right away

> Here, we need GitHub Action workflow for linting. Right?


Yes we do need an workflow for linting and also you need to fix the currently existing issues (shown in the above screen-shot) that occurs when running a linter so that the GitHub actions checks may pass.

@abhishekraj272 should we remove the `dev()`function as it was used just for temporary testing and is currently being flagged by the linter

**Comment by abskrj** [comment]
yes, we can remove the `dev` function now

**Comment by Shofiya2003** [comment]
Hey! 
- first I should resolve the errors we get when we run golangci-lint 
- use GitHub actions to set up the workflow for golang ci lint actions

**Comment by uzaxirr** [comment]
> Hey!
> 
> * first I should resolve the errors we get when we run golangci-lint
> * use GitHub actions to set up the workflow for golang ci lint actions

Sounds like a plan!

**Comment by chauhan17nitin** [comment]
> > Hey!
> > 
> > * first I should resolve the errors we get when we run golangci-lint
> > * use GitHub actions to set up the workflow for golang ci lint actions
> 
> Sounds like a plan!

Have a suggestion here :thinking: , may be you guys can decide on it accordingly :sweat_smile: 

i see if we will start resolving golangci-lint error here, that may take considerable amount of time, + at the same time other people will be committing un-linted code,

there is a param `issues` in golang-ci-lint configuration
if we mark the `new` inside it as true, then it will only analyze the new coming code that it is correctly linted on not.

At first we can start with that and create a pipeline :green_circle:  so that new coming code is correct, later on when old files code will be edited linting will come into play :smile: .

Just wanted to say we can do it progressively instead of resolving all errors in one go (which may be frustrating sometimes :disappointed: ).

At the end decision will be yours :100: .

**Comment by abskrj** [comment]
Yeah, sounds good

**Comment by Shofiya2003** [comment]
Alrighty
